name: animated_rotation
description: An implicit animation widget for rotation. Just provide the angle and the widget will rotate over time.
version: 1.0.0
author: Jason Rai <jason.c.rai@gmail.com>
homepage: https://github.com/MisterJimson/animated_rotation

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: